import React from 'react';
import { motion } from 'framer-motion';

export default function ContributionsPage({ isLoggedIn, setShowAuthModal, setShowContributionModal }) {
  return (
    <section className="py-5"><div className="container"><div className="d-flex justify-content-between align-items-center mb-4"><h3 className="section-title mb-0"><i className="bi bi-pencil-square text-primary me-2" />Mes Contributions</h3><button className="btn btn-primary rounded-pill px-4" onClick={() => { if (!isLoggedIn) { setShowAuthModal(true); return; } setShowContributionModal(true); }}><i className="bi bi-plus-circle me-2" />Nouvelle contribution</button></div>
    {isLoggedIn ? <div className="row g-4">{[{ id: 1, type: "ajout", etablissement: "Pharmacie Al Hayat", statut: "en_attente", date: "25/04/2026" }, { id: 2, type: "modification", etablissement: "Clinique Badr", statut: "valide", date: "20/04/2026" }, { id: 3, type: "ajout", etablissement: "Hôpital Al Farabi", statut: "refuse", date: "15/04/2026" }].map(c => <div className="col-md-6" key={c.id}><motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} className="card border-0 shadow-sm" style={{ borderRadius: 16, overflow: "hidden" }}><div className="card-body p-4"><div className="d-flex justify-content-between align-items-start mb-3"><span className={`badge rounded-pill px-3 py-2 ${c.type === "ajout" ? "bg-primary" : "bg-info"}`}><i className={`bi ${c.type === "ajout" ? "bi-plus-circle" : "bi-pencil"} me-1`} />{c.type === "ajout" ? "Ajout" : "Modification"}</span><span className={`badge rounded-pill px-3 py-2 ${c.statut === "valide" ? "bg-success-subtle text-success" : c.statut === "refuse" ? "bg-danger-subtle text-danger" : "bg-warning-subtle text-warning"}`}><i className="bi bi-circle-fill me-1" style={{ fontSize: 6 }} />{c.statut === "valide" ? "Validée" : c.statut === "refuse" ? "Refusée" : "En attente"}</span></div><h6 style={{ fontWeight: 700, marginBottom: 4 }}>{c.etablissement}</h6><p style={{ fontSize: "0.85rem", color: "var(--gray-500)", marginBottom: 0 }}><i className="bi bi-calendar3 me-1" />{c.date}</p></div></motion.div></div>)}</div> : <div className="text-center py-5"><i className="bi bi-person-lock" style={{ fontSize: "4rem", color: "var(--gray-300)" }} /><h5 className="mt-3" style={{ color: "var(--gray-500)" }}>Connectez-vous pour gérer vos contributions</h5><button className="btn btn-primary rounded-pill mt-3 px-4" onClick={() => setShowAuthModal(true)}><i className="bi bi-person-fill me-1" />Se connecter</button></div>}
    </div></section>
  );
}