import React from 'react';
import Map from '../components/Map.js';
import { typeIcons, typeLabels, typeBadge } from '../data/mockData.js';
import StarRating from '../components/StarRating.js';

export default function MapPage(props) {
  return (
    <>
      <div className="py-4" style={{ background: "#fff" }}><div className="container"><h3 className="section-title mb-4"><i className="bi bi-map-fill text-primary me-2" />Carte Interactive</h3><div className="search-container" style={{ marginTop: 0, marginBottom: "1.5rem" }}><div className="row g-3 align-items-center"><div className="col-lg-5"><div className="position-relative"><i className="bi bi-search position-absolute" style={{ left: 14, top: "50%", transform: "translateY(-50%)", color: "var(--gray-500)", fontSize: "1.1rem" }} /><input type="text" className="search-input-custom" style={{ paddingLeft: 44 }} placeholder="Rechercher par nom ou ville..." value={props.searchQuery} onChange={e => props.setSearchQuery(e.target.value)} /></div></div><div className="col-lg-3"><select className="search-input-custom" style={{ cursor: "pointer" }} value={props.activeStatusFilter} onChange={e => props.setActiveStatusFilter(e.target.value)}><option value="all">🕐 Tous les statuts</option><option value="ouvert">🟢 Ouvert</option><option value="ferme">🔴 Fermé</option></select></div><div className="col-lg-2"><button className="btn-near-me w-100" onClick={props.handleNearMe} disabled={props.geoLoading}>{props.geoLoading ? <><span className="spinner-border spinner-border-sm me-2" />...</> : <><i className="bi bi-crosshair me-2" />Near Me</>}</button></div><div className="col-lg-2"><button className="btn-search w-100"><i className="bi bi-search me-2" />Filtrer</button></div></div><div className="filter-pills">{["pharmacie", "clinique", "hopital"].map(type => <button key={type} className={`filter-pill ${props.activeFilters.includes(type) ? "active" : ""}`} onClick={() => props.handleFilterToggle(type)}><i className={`bi ${typeIcons[type]} me-1`} />{typeLabels[type]}</button>)}</div></div></div></div>
      <Map {...props} />
      <div className="py-4"><div className="container"><div className="d-flex justify-content-between align-items-center mb-3"><h6 style={{ fontWeight: 600, color: "var(--gray-700)" }}>Résultats : <span style={{ color: "var(--primary)" }}>{props.filteredEtablissements.length}</span> établissement(s)</h6><button className="btn btn-sm btn-outline-primary rounded-pill" onClick={() => props.setCurrentPage("list")}>Voir en liste <i className="bi bi-list-ul ms-1" /></button></div><div className="row g-3">{props.filteredEtablissements.map(e => <div className="col-md-4" key={e.id}><div className="card border-0 shadow-sm" style={{ borderRadius: 14, cursor: "pointer" }} onClick={() => props.openDetail(e)}><div className="card-body p-3"><div className="d-flex justify-content-between align-items-start mb-2"><h6 style={{ fontWeight: 700, fontSize: "0.95rem", margin: 0 }}>{e.nom}</h6><span className={`badge ${typeBadge[e.type]} rounded-pill`} style={{ fontSize: "0.7rem" }}>{typeLabels[e.type]}</span></div><div style={{ fontSize: "0.8rem", color: "var(--gray-500)" }}><i className="bi bi-geo-alt-fill text-primary me-1" />{e.adresse}</div><div className="d-flex justify-content-between align-items-center mt-2"><StarRating rating={e.rating} size="sm" /><span className={`badge ${e.etat === "ouvert" ? "bg-success-subtle text-success" : "bg-danger-subtle text-danger"} rounded-pill`} style={{ fontSize: "0.7rem" }}>{e.etat}</span></div></div></div></div>)}</div></div></div>
    </>
  );
}